### ISSUE TITLE
Theme for D8 version of site

### ISSUE THREAD

**Issue by onelittlebecca** [Drupal4Gov/drupal4gov.us#10]
We need to get a theme for the D8 version of the site going. Jon, you originally volunteered as tribute, do you need us to get some people to help you? We had some people at the Gov BoF volunteer their time and their teams. Thoughts?

**Comment by afarazdaghi** [comment]
I had volunteered at the Gov BoF and have some folks that can help. Let me know what I can do. (We are currently looking at whether we can implement the US Web Standards (https://standards.usa.gov/) in D8 using Pattern Lab)

**Comment by jdearie** [comment]
@afarazdaghi - that would be fantastic.  @jonraedeke can you fill us in on how far you've gotten?  We have our logo that I would like to keep since we've been using it on print materials etc... but otherwise, we're open to ideas.  The PDF of the original branding idea is linked below

https://drive.google.com/file/d/0B0DugWY2OexQdU9vT09iV2tJYmJ6M1dIM3NJbkQ1Y21kcnZN/view?usp=sharing

**Comment by jonraedeke** [comment]
@afarazdaghi Yes, thanks for offering to help! Here's what I've done so far:
- #12 
- #13 

It would be great if you could help get some gulp tasks and patternlab setup into the child theme. Right now, this repo is just an issue tracker. We can add you to the Acquia cloud code repo if you like. The general workflow is outlined here #8

**Comment by charlieartist** [comment]
Unless you're wedded to PatternLab, the Cog base theme includes KSSnode built it, and will generate the styleguide elements automatically.

**Comment by jonraedeke** [comment]
@charlieartist I also like the simplicity and flexibility of KSS over PatternLab. I would like to stick with using the U.S. Web Design Standards as a base theme so we can contribute to work there. Also, that gets us pretty far on all the element styles. I think it would be good to steal the KSS setup and gulp tasks of Cog and put them in our child theme.

**Comment by afarazdaghi** [comment]
@jonraedeke Sounds good, I will review and catch up on what you've done. I also have a few developers on my team that could help (I'm more of a back-end dev than a themer). How would you like to handle access to the repo and Acquia environment? 

@charlieartist I'm open to options and will look into KSSnode as well - I have not used it in the past.

**Comment by onelittlebecca** [comment]
Hey guys, where do we stand on all of this? 
As DGC approaches, figure we should check in and get an update on how its going.

**Comment by onelittlebecca** [comment]
@jonraedeke @charlieartist -- I think I had discussed with jon about having a design proof ready for preview in the next 2-3 weeks -- does this still seem feasible? can we set a preview of a proof for 2 weeks out? Around 8/17 or 8/18?

**Comment by jonraedeke** [comment]
@onelittlebecca I think @charlieartist  and I are going to come up with a plan for how to unify D4G and Drupal GovCon visual. I think that strategy is the thing we can probably show in a few weeks. Sound good Karl?

**Comment by charlieartist** [comment]
Yes Jon, sounds good!

Karl Kaufmann
Creative Communication
http://www.karlkaufmann.com

**Comment by onelittlebecca** [comment]
How we lookin?

**Comment by onelittlebecca** [comment]
@jonraedeke @charlieartist hows it lookin? any progress updates?

**Comment by onelittlebecca** [comment]
any update on progress for new theme?

**Comment by onelittlebecca** [comment]
Closing this out. It can be revisited at another time but for now we need to move forward, so going to use a solid base theme and sort it all out as we go. flying by the seats of our pants -- LIKE BOSSES.
