### ISSUE TITLE
create event type vocabulary

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/drupal4gov.us#15]
create an event type vocabulary that can be used with the event content type.

initial terms should be:

Conference
Half-Day
Webinar

**Comment by jonraedeke** [comment]
@jdearie I was finally able to push this configuration change. I realized Acquia has it's own naming convention for the config directory. https://docs.acquia.com/acquia-cloud/develop/config-d8

For reference, here are the steps to pushing config to dev:
1. Make a config change locally
2. `drush cex vcs` (export)
3. commit the changes to a branch and push the branch to origin
4. switch Dev environment to your new branch 
5. `drush @drupal4gov.dev cim vcs` (import)
6. If it works well, merge your branch into master and switch the dev branch back to master

**Comment by jonraedeke** [comment]
This is deployed, feel free to add the terms on prod.
