### ISSUE TITLE
Travis => Acquia Cloud Deployment Issue

### ISSUE THREAD

**Issue by mikemadison13** [Drupal4Gov/drupal4gov.us#21]
Something is causing travis builds to not properly deploy to the cloud. I think we are missing a ssh linkage between the apps.

**Comment by onelittlebecca** [comment]
I BELIEVE IN YOU !

**Comment by onelittlebecca** [comment]
Travis seems like a dick. Just sayin

**Comment by onelittlebecca** [comment]
Did we ever get this sorted?  Is this the hold up from upgrading to D8 from D7?

**Comment by onelittlebecca** [comment]
and have all of these issues moved to Jira? if so, I am going to move over there.

**Comment by mikemadison13** [comment]
@onelittlebecca we have moved, i'm not sure that all the tickets have been moved (but theoretically?)

**Comment by onelittlebecca** [comment]
aight, will head over there. I know Kat gave me access.

**Comment by mikemadison13** [comment]
resolved by migrating to acquia pipelines.
