### ISSUE TITLE
Remove problematic Presenters display from attendees views

### ISSUE THREAD

**Issue by brooke-heaton** [Drupal4Gov/drupal4gov.us#22]
This display has issues with duplicate values and should be revised or overhauled. Other displays should be evaluated and kept if working.

**Comment by onelittlebecca** [comment]
@bheatonf1 did you mean to put this in d4g or dgc issue queue?

**Comment by onelittlebecca** [comment]
think this was supposed to go in dgc issue queue -- moving it there.
