### ISSUE TITLE
Make Session video display

### ISSUE THREAD

**Issue by brooke-heaton** [Drupal4Gov/drupal4gov.us#23]
Session videos currently display as a link. Make the link an embed and provide a link as well. 
Example: https://www.drupalgovcon.org/program/sessions/create-truly-remarkable-data-visualizations-d3

![youtube_link](https://user-images.githubusercontent.com/19474864/28996334-8f8a3e8c-79cc-11e7-9339-4d10a1368edc.png)

**Comment by onelittlebecca** [comment]
Hey @brooke-heaton wrong issue queue im guessing?

**Comment by onelittlebecca** [comment]
Closing this. Moved to 2017 DGC issue queue

**Comment by brookeheaton** [comment]
@onelittlebecca Yep - you are correct. That was for DGC - my bad and thanks!!

**Comment by onelittlebecca** [comment]
see? i know things... sometimes :-P and no worries! so many repos!
