### ISSUE TITLE
Twig Debugging is active in Production.

### ISSUE THREAD

**Issue by bmartinez287** [Drupal4Gov/drupal4gov.us#245]
It's a pretty site but someone forgot to turn off twig debugging annotations.
![Screenshot 2024-04-02 at 11 26 18 PM](https://github.com/Drupal4Gov/drupal4gov.us/assets/39039024/e5695862-a9f0-4f7b-a05d-324674e29cdb)

**Comment by bmartinez287** [comment]
pretty cool it uses SDC.

**Comment by CNDexter** [comment]
Thank you @bmartinez287 for flagging this. It is resolved!
