### ISSUE TITLE
Webinar Streaming

### ISSUE THREAD

**Issue by onelittlebecca** [Drupal4Gov/drupal4gov.us#6]
Install a way that we can stream webinars from the site (whether it is embedded in the website or there is some functionality linking off)

**Comment by jdearie** [comment]
when a webinar is live, we can provide the link to the conference (zoom vs join.me or whatever).  

I think we can then store them in our YouTube account and link to them from a "Webinars" page... which could be a view that filters events based on type Webinar. 

relates to #14

**Comment by onelittlebecca** [comment]
ok, sounds good. And a webinar schedule -- should i open a new ticket for schedule? or i think we have an events ticket open.
