### ISSUE TITLE
Lightning Updates

### ISSUE THREAD

**Issue by charlieartist** [Drupal4Gov/drupal4gov.us#64]
Current site build in on Acquia Lightning, and is out-of-date requiring security updates, and will need to be patched soon.

**Comment by mikemadison13** [comment]
note that we are running drupal/core 8.8.4 as of https://github.com/Drupal4Gov/drupal4gov.us/pull/60. there should be no outstanding security updates on the site.

**Comment by charlieartist** [comment]
Agreed.
