### ISSUE TITLE
Create Blog Content Type

### ISSUE THREAD

**Issue by onelittlebecca** [Drupal4Gov/drupal4gov.us#7]
Create a blog content type with Title, Body, Author, Date, etc

**Comment by onelittlebecca** [comment]
Jess has done this, just needs to push it up. Poking her

**Comment by mikemadison13** [comment]
this might need to be redone, given that we are now in a BLT environment. you might be able to push your configuration from whatever you did previously @jdearie i'm happy to have a look.
