### ISSUE TITLE
Decide on a workflow

### ISSUE THREAD

**Issue by onelittlebecca** [Drupal4Gov/drupal4gov.us#8]
We need to decide on a workflow so that we don't overwrite each other's things when pushing from local to dev. If there isn't a ticket or we don't check it out, how will we know when someone is pushing something up?  This kind of coordination needs to happen since the issue queue isn't connected to git :-)

**Comment by onelittlebecca** [comment]
Bueller?

**Comment by jonraedeke** [comment]
OK, let's keep this simple at least for now. Here's the workflow I propose:
- Code in Acquia cloud git repo
- Local development done via Dev Desktop
- Issues in GitHub
- Each GitHub issue gets a branch in the Acquia repo (this branch would be `D4G-8`)
- Commit messages in the Acquia repo would look like `D4G-12: Updated core to 8.3.3`
- To test branches, we can switch the DEV environment in the Acquia cloud UI
- After the branch is tested on DEV, it can be merged into the `master` branch
- `master` branch on the DEV environment should always be production ready
- `master` is deployed to STAGING and then PROD
- A fresh prod DB can always be dragged down to STAGING or DEV.
- Communicate via Slack, we can have Acquia report to Slack automatically too.

@onelittlebecca @jdearie sounds good?

**Comment by jonraedeke** [comment]
The dev environment is now set to the master branch.

**Comment by jdearie** [comment]
I like it.

I use github all by myself, so I haven't done a lot with branching and merging. I need to learn :)

**Comment by afarazdaghi** [comment]
@jonraedeke @jdearie Would you want to incorporate a hook into github so that the code is also pushed to this repository? (or make github the primary and have the hook push to Acquia on every commit) - it would allow the commits to the more closely tied to the issue queue.

**Comment by jonraedeke** [comment]
@afarazdaghi @jdearie On second thought, we may need to go ahead and use [Acquia BLT](https://github.com/acquia/blt) for this project. It adds complexity to the workflow, but having the code in GitHub will help us work with a broader team of volunteers. My previously suggested setup was based on a small group of contributors.

**Comment by onelittlebecca** [comment]
this sounds like a good idea re: incorporating Acquia BLT -- code repo up to date is important as more get involved. Was this ever set up?

**Comment by onelittlebecca** [comment]
solid. can we merge this with issue 17 and call this one solved re workflow questions? :-)

**Comment by jonraedeke** [comment]
Yep, I think BLT dictates/allows a nice dev workflow.
