### ISSUE TITLE
Create a Press Release or News Content Type

### ISSUE THREAD

**Issue by onelittlebecca** [Drupal4Gov/drupal4gov.us#9]
Create a Press Release or News Content Type

**Comment by afarazdaghi** [comment]
@onelittlebecca - We created the press release and announcement content types below for HHS - we can port these to D8 if they are satisfactory. 

https://github.com/HHS/Structured-Content-News-Release
https://github.com/HHS/Structured-Content-Announcement

**Comment by onelittlebecca** [comment]
@afarazdaghi yea, the news release feature type would work. If you can't port them, maybe @mikemadison13 can take a look in a week when he is working on the D8 site.

adding to spreadsheet :-P
